version: '3.5'
services:
  php:
    restart: always
    build: .
    container_name: laundry
    volumes:
      - "./:/var/www/html"
    ports:
      - "70:80"
    environment:
      APP_NAME: blog
      APP_ENV: local
      APP_KEY: 'base64:YLHQ3eRNyhMOShImw7bG1vdHHwERtkQgemTHCTtF8dU='
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laundry
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_WRITE_HOST: database
      DB_READ_HOST: database

  database:
    # platform: linux/amd64
    # image: arm64v8/mysql:8
    image: mysql:8
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laundry
      MYSQL_USER: root
      MYSQL_PASSWORD: root 

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_laundry
    restart: always
    ports:
      - 7777:80
    links:
      - database
    environment:
      PMA_HOST: database 
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 3000M

volumes:
  db-data: {}
